import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { BackgroundBeams } from "@/components/ui/background-beams";
import { Toaster } from "@/components/ui/toaster";
import { ModeToggle } from "@/components/mode-toogle";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Certicheck",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <div className="fixed top-0 flex w-full mx-auto py-4 px-8 justify-between z-20">
            <div className="text-xl font-bold">
              <Link href={"/"}>Certicheck</Link>
            </div>
            <ModeToggle />
          </div>
          <div className="h-screen w-screen px-4 bg-slate-200 dark:bg-neutral-950 relative">
            <div className="z-10 w-full max-w-[1440px] mx-auto h-full flex flex-col items-center justify-center antialiased relative">
              {children}
            </div>
          </div>
          <Toaster />
          <BackgroundBeams />
        </ThemeProvider>
      </body>
    </html>
  );
}
